export const COLORS = {
  primary: '#001e40',
  primaryContainer: '#003366',
  secondary: '#006c47',
  secondaryContainer: '#8af5be',
  surface: '#f9f9fa',
  surfaceContainer: '#edeeef',
  surfaceContainerLow: '#f3f3f4',
  surfaceContainerHigh: '#e8e8e9',
  surfaceContainerHighest: '#e2e2e3',
  surfaceContainerLowest: '#ffffff',
  onSurface: '#1a1c1d',
  onSurfaceVariant: '#43474f',
  outline: '#737780',
  outlineVariant: '#c3c6d1',
  onPrimary: '#ffffff',
  onSecondary: '#ffffff',
  onPrimaryContainer: '#799dd6',
  surfaceTint: '#3a5f94',
  error: '#ba1a1a',
} as const;
